import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import { buildAntigravityLauncherFile } from './antigravity-launcher.js';
import { buildGrokBuildLauncherFile } from './grok-build-launcher.js';
import {
    buildLauncherFile,
    buildPosixLauncherScript,
    buildWindowsLauncherScript,
    formatHandoffPath,
    launcherExtension,
    powershellSingleQuote,
    shellSingleQuote,
} from './launch-script.js';

/** One frozen launcher: the input and the exact bytes the pre-refactor builders produced for each platform. */
interface LauncherSnapshot<T> {
    input: T;
    darwin: string;
    win32: string;
}

/**
 * Launchers generated by the Grok Build and Antigravity CLI builders before they moved onto `launch-script.ts`.
 * Regenerating this file defeats the test: it exists to prove the shared builder writes the same bytes.
 */
const SNAPSHOTS: {
    grok: Record<string, LauncherSnapshot<Parameters<typeof buildGrokBuildLauncherFile>[0]>>,
    antigravity: Record<string, LauncherSnapshot<Parameters<typeof buildAntigravityLauncherFile>[0]>>,
} = JSON.parse(fs.readFileSync(new URL('./__fixtures__/launcher-snapshots.json', import.meta.url), 'utf8'));

/**
 * Decode the PowerShell program inside a `.cmd` launcher.
 *
 * @param {string} script `.cmd` contents.
 * @returns {string} The UTF-16LE program passed to `-EncodedCommand`.
 */
function decodeProgram(script: string) {
    const encoded = script.match(/-EncodedCommand\s+(\S+)/)?.[1];
    assert.ok(encoded, 'launcher has no -EncodedCommand');
    return Buffer.from(encoded, 'base64').toString('utf16le');
}

test('Grok Build launchers are byte-identical to the pre-refactor snapshots', () => {
    for (const [name, snapshot] of Object.entries(SNAPSHOTS.grok)) {
        assert.equal(buildGrokBuildLauncherFile(snapshot.input, 'darwin'), snapshot.darwin, `grok ${name} darwin`);
        assert.equal(buildGrokBuildLauncherFile(snapshot.input, 'win32'), snapshot.win32, `grok ${name} win32`);
    }
});

test('Antigravity CLI launchers are byte-identical to the pre-refactor snapshots', () => {
    for (const [name, snapshot] of Object.entries(SNAPSHOTS.antigravity)) {
        assert.equal(buildAntigravityLauncherFile(snapshot.input, 'darwin'), snapshot.darwin, `agy ${name} darwin`);
        assert.equal(buildAntigravityLauncherFile(snapshot.input, 'win32'), snapshot.win32, `agy ${name} win32`);
    }
});

test('shell quoting escapes single quotes for bash and PowerShell', () => {
    assert.equal(shellSingleQuote(`it's`), `'it'\\''s'`);
    assert.equal(powershellSingleQuote(`it's`), `'it''s'`);
});

test('bash launcher: bare flags, quoted values, -- and a prefixed prompt read from disk', () => {
    const script = buildPosixLauncherScript({
        command: '/opt/bin/cli',
        cwd: "/tmp/it's",
        promptPath: '/tmp/p.txt',
        args: [{ flag: '--mode' }, { value: 'a b' }, { value: '/tmp/root' }, { prompt: true, prefix: '--prompt=' }, { endOfOptions: true }, { prompt: true }],
    });
    assert.equal(script, [
        '#!/bin/bash',
        'set -euo pipefail',
        "cd '/tmp/it'\\''s' || exit 1",
        `exec '/opt/bin/cli' --mode 'a b' '/tmp/root' --prompt="$(cat '/tmp/p.txt')" -- "$(cat '/tmp/p.txt')"`,
        '',
    ].join('\n'));
});

test('PowerShell launcher: quoted --, the prompt variable, and a prefixed prompt as one string', () => {
    const script = buildWindowsLauncherScript({
        command: 'C:\\bin\\cli.exe',
        cwd: 'C:\\repo',
        promptPath: 'C:\\repo\\p.txt',
        args: [{ value: 'C:\\repo' }, { prompt: true, prefix: '--prompt=' }, { endOfOptions: true }, { prompt: true }],
    });
    assert.match(script, /^@echo off\r\npowershell\.exe -NoProfile -ExecutionPolicy Bypass -EncodedCommand \S+\r\n$/);
    assert.equal(decodeProgram(script), [
        "Set-Location -LiteralPath 'C:\\repo'",
        "$prompt = Get-Content -LiteralPath 'C:\\repo\\p.txt' -Raw -Encoding UTF8",
        `& 'C:\\bin\\cli.exe' 'C:\\repo' "--prompt=$prompt" '--' $prompt`,
    ].join('; '));
});

test('launchers reject a bare token that could change the command', () => {
    const base = { command: 'cli', cwd: '/tmp', promptPath: '/tmp/p.txt' };
    for (const flag of ['--x; rm -rf /', '$(id)', '--a b', '', 'plain']) {
        assert.throws(() => buildPosixLauncherScript({ ...base, args: [{ flag }] }), /Unsafe launcher token/, flag);
        assert.throws(() => buildWindowsLauncherScript({ ...base, args: [{ flag }] }), /Unsafe launcher token/, flag);
    }
    assert.throws(() => buildPosixLauncherScript({ ...base, args: [{ prompt: true, prefix: '--p="' }] }), /Unsafe launcher token/);
});

test('launcherExtension and buildLauncherFile pick the platform', () => {
    const input = { command: 'cli', cwd: '/tmp', promptPath: '/tmp/p.txt', args: [] };
    assert.equal(launcherExtension('win32'), '.cmd');
    assert.equal(launcherExtension('darwin'), '.command');
    assert.equal(launcherExtension('linux'), '.command');
    assert.match(buildLauncherFile(input, 'linux'), /^#!\/bin\/bash\n[\s\S]*\nexec 'cli'\n$/);
    assert.match(buildLauncherFile(input, 'win32'), /^@echo off\r\n/);
});

test('formatHandoffPath keeps cwd-relative paths and falls back to absolute', () => {
    assert.equal(formatHandoffPath('/tmp/repo/.intent-inspector/requests/a.md', '/tmp/repo', 'relative'), '.intent-inspector/requests/a.md');
    assert.equal(formatHandoffPath('/elsewhere/a.md', '/tmp/repo', 'relative'), '/elsewhere/a.md');
    assert.equal(formatHandoffPath('/tmp/repo/a.md', '/tmp/repo', 'absolute'), '/tmp/repo/a.md');
});
