import js from '@eslint/js';
import tseslint from 'typescript-eslint';

// Flat ESLint config for the plugin repo. Parsing uses the classic TypeScript 5.x compiler
// provided to typescript-eslint by .pnpmfile.mjs (the repo itself compiles with TypeScript 7,
// which has no JS compiler API). The custom rules encode the conventions in AGENTS.md: named
// exports only, no `any`, no @ts-* escapes, files capped at 400 non-test lines.
export default tseslint.config(
    {
        ignores: [
            'dist/**',
            'demo/**',
            'node_modules/**',
            'coverage/**',
            '.stamp-parity/**',
            'media/**',
            'promo/**',
            'docs/**',
        ],
    },
    js.configs.recommended,
    ...tseslint.configs.recommended,
    {
        files: ['src/**/*.ts', 'scripts/**/*.ts'],
        languageOptions: {
            globals: {
                console: 'readonly',
                process: 'readonly',
                Buffer: 'readonly',
                URL: 'readonly',
                URLSearchParams: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
                setInterval: 'readonly',
                clearInterval: 'readonly',
                queueMicrotask: 'readonly',
                fetch: 'readonly',
                structuredClone: 'readonly',
                TextEncoder: 'readonly',
                TextDecoder: 'readonly',
                AbortController: 'readonly',
                AbortSignal: 'readonly',
            },
        },
        rules: {
            // AGENTS.md: named exports only (exceptions exist where the host requires default).
            'no-restricted-syntax': [
                'error',
                {
                    selector: 'ExportDefaultDeclaration',
                    message: 'AGENTS.md: named exports only — `export default` is reserved for host-required APIs (webpack / Next.js loaders).',
                },
            ],
            '@typescript-eslint/no-explicit-any': 'error',
            '@typescript-eslint/ban-ts-comment': [
                'error',
                {
                    'ts-expect-error': true,
                    'ts-ignore': true,
                    'ts-nocheck': true,
                },
            ],
            '@typescript-eslint/no-unused-vars': [
                'error',
                { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' },
            ],
        },
    },
    {
        files: ['src/client/**/*.ts'],
        languageOptions: {
            globals: {
                window: 'readonly',
                document: 'readonly',
                navigator: 'readonly',
                location: 'readonly',
                HTMLElement: 'readonly',
                HTMLTextAreaElement: 'readonly',
                HTMLInputElement: 'readonly',
                HTMLDivElement: 'readonly',
                HTMLButtonElement: 'readonly',
                Element: 'readonly',
                Node: 'readonly',
                NodeListOf: 'readonly',
                MutationObserver: 'readonly',
                IntersectionObserver: 'readonly',
                ResizeObserver: 'readonly',
                requestAnimationFrame: 'readonly',
                cancelAnimationFrame: 'readonly',
                getComputedStyle: 'readonly',
                CustomEvent: 'readonly',
                Event: 'readonly',
                KeyboardEvent: 'readonly',
                MouseEvent: 'readonly',
                PointerEvent: 'readonly',
                WheelEvent: 'readonly',
                DragEvent: 'readonly',
                ClipboardEvent: 'readonly',
                FocusEvent: 'readonly',
                InputEvent: 'readonly',
                TouchEvent: 'readonly',
                DOMRect: 'readonly',
                DOMParser: 'readonly',
                DocumentFragment: 'readonly',
                ShadowRoot: 'readonly',
                Text: 'readonly',
                Comment: 'readonly',
                Range: 'readonly',
                Selection: 'readonly',
                alert: 'readonly',
                confirm: 'readonly',
                prompt: 'readonly',
                localStorage: 'readonly',
                sessionStorage: 'readonly',
                performance: 'readonly',
                crypto: 'readonly',
                Image: 'readonly',
                ImageData: 'readonly',
                OffscreenCanvas: 'readonly',
                HTMLCanvasElement: 'readonly',
                CanvasRenderingContext2D: 'readonly',
                HTMLImageElement: 'readonly',
                HTMLVideoElement: 'readonly',
                HTMLScriptElement: 'readonly',
                HTMLStyleElement: 'readonly',
                HTMLAnchorElement: 'readonly',
                HTMLSpanElement: 'readonly',
                HTMLIFrameElement: 'readonly',
                HTMLSelectElement: 'readonly',
                HTMLOptionElement: 'readonly',
                FileReader: 'readonly',
                Blob: 'readonly',
                File: 'readonly',
                FormData: 'readonly',
                XMLHttpRequest: 'readonly',
                WebSocket: 'readonly',
                Worker: 'readonly',
                MessageChannel: 'readonly',
                MessagePort: 'readonly',
                BroadcastChannel: 'readonly',
                history: 'readonly',
                screen: 'readonly',
                matchMedia: 'readonly',
                MediaQueryList: 'readonly',
                atob: 'readonly',
                btoa: 'readonly',
                CSS: 'readonly',
                CSSStyleSheet: 'readonly',
                CSSStyleDeclaration: 'readonly',
                CSSRule: 'readonly',
                visualViewport: 'readonly',
                Document: 'readonly',
                DocumentType: 'readonly',
            },
        },
    },
    {
        files: ['scripts/**/*.mjs'],
        languageOptions: {
            globals: {
                console: 'readonly',
                process: 'readonly',
                Buffer: 'readonly',
                URL: 'readonly',
                setTimeout: 'readonly',
                clearTimeout: 'readonly',
            },
        },
    },
    {
        // AGENTS.md red line: files MUST be split once they exceed 400 lines. Applies to
        // non-test source only (tests are exempt, matching the audit that flagged ten files).
        files: ['src/**/*.ts', 'scripts/**/*.ts'],
        ignores: ['**/*.test.ts'],
        rules: {
            'max-lines': ['error', { max: 400, skipBlankLines: false, skipComments: false }],
        },
    },
    {
        // Webpack / Next.js loaders must default-export their entry — the host requires it.
        files: ['src/server/**/*-loader.ts'],
        rules: {
            'no-restricted-syntax': 'off',
        },
    },
    {
        files: ['**/*.test.ts', 'demo/**/*.ts'],
        rules: {
            'no-restricted-syntax': 'off',
            '@typescript-eslint/no-explicit-any': 'off',
            'max-lines': 'off',
        },
    },
);
