/**
 * The generated `'use client'` module that installs the inspector in a Next.js page.
 *
 * Purpose: loaders only add an import of this file (a stable path), so their output never depends on the per-process
 * token or port and stays cache-safe under Turbopack's persistent cache. The file itself carries the live bootstrap
 * statement and is rewritten whenever the inspector server (re)starts; the bundler's file watcher hot-reloads it.
 *
 * Boundary: lives under the plugin output dir (`.intent-inspector/next/`, git-ignored by a local `.gitignore`). Writes
 * are skipped when the content is unchanged and use temp-file + rename so watchers never see a half-written module.
 * A module that still points at a live inspector server (another `next dev` of the same project) is worth keeping; the
 * helpers below let the writer detect that instead of clobbering it.
 */

import fs from 'node:fs';
import path from 'node:path';
import { ENDPOINTS } from '../../shared/constants.js';
import { BOOTSTRAP_IDENTIFIER } from './entry-inject.js';

/** Hosts a bootstrap module may point at; anything else is never probed. */
const LOOPBACK_HOSTS = new Set(['127.0.0.1', 'localhost', '[::1]']);

/** File name of the bootstrap module inside `<outputDir>/next/`. */
export const NEXT_BOOTSTRAP_FILE = 'bootstrap.js';

/**
 * Source of the bootstrap module.
 *
 * @param {string | null} statement Output of `runtime.bootstrapStatement()`, or `null` for the placeholder written
 *   before the server listens (a valid module that installs nothing, so an early compile never fails to resolve it).
 * @returns {string} Module source: `'use client'`, the statement, and a component that renders nothing.
 */
export function bootstrapModuleSource(statement: string | null) {
    return [
        "'use client';",
        '// Generated by ide-byebye for `next dev`; rewritten on every dev-server start. Do not edit or commit.',
        statement ?? '// ide-byebye: inspector server is starting…',
        `export default function ${BOOTSTRAP_IDENTIFIER}() {`,
        '    return null;',
        '}',
        '',
    ].join('\n');
}

/**
 * Write a file only when its content differs, atomically.
 *
 * @param {string} file Absolute target path; parent directories are created.
 * @param {string} content Desired content.
 * @returns {boolean} `true` when the file was (re)written.
 */
export function writeFileIfChanged(file: string, content: string) {
    try {
        if (fs.readFileSync(file, 'utf8') === content)
            return false;
    }
    catch {
        // missing file → write below
    }
    fs.mkdirSync(path.dirname(file), { recursive: true });
    const tmp = `${file}.${process.pid}.${Date.now()}.tmp`;
    fs.writeFileSync(tmp, content, 'utf8');
    fs.renameSync(tmp, file);
    return true;
}

/**
 * Write the bootstrap module (and a `.gitignore` next to it so it is never committed by accident).
 *
 * @param {string} file Absolute bootstrap module path (`<outputDir>/next/bootstrap.js`).
 * @param {string | null} statement Bootstrap statement, or `null` for the placeholder.
 * @returns {boolean} `true` when the module content changed.
 */
export function writeBootstrapModule(file: string, statement: string | null) {
    writeFileIfChanged(path.join(path.dirname(file), '.gitignore'), '*\n');
    return writeFileIfChanged(file, bootstrapModuleSource(statement));
}

/**
 * Client bundle URL embedded in a bootstrap module (or statement) source.
 *
 * @param {string} content Module or statement source produced by this package.
 * @returns {string | null} The `script.src` URL, or `null` for placeholders / foreign content.
 */
export function readBootstrapClientSrc(content: string) {
    return /script\.src = "([^"]+)"/.exec(String(content ?? ''))?.[1] ?? null;
}

/**
 * Whether the inspector server behind a bootstrap client URL is alive and still accepts its token.
 *
 * Boundary: only loopback URLs are probed (the value comes from a file on disk); anything else counts as dead. A
 * refused connection or the timeout also counts as dead, so a stale module from a finished session is replaced.
 *
 * @param {string} clientSrc `script.src` from {@link readBootstrapClientSrc}.
 * @param {number} [timeoutMs] Probe timeout.
 * @returns {Promise<boolean>} `true` when `/ping` answered 200 for that token.
 */
export async function isBootstrapServerAlive(clientSrc: string, timeoutMs = 800) {
    let url: URL;
    try {
        url = new URL(clientSrc);
    }
    catch {
        return false;
    }
    const token = url.searchParams.get('token');
    if (!token || url.protocol !== 'http:' || !LOOPBACK_HOSTS.has(url.hostname))
        return false;
    try {
        const res = await fetch(`${url.origin}${ENDPOINTS.ping}?token=${encodeURIComponent(token)}`, {
            signal: AbortSignal.timeout(timeoutMs),
        });
        return res.ok;
    }
    catch {
        return false;
    }
}
